exec(open('t437.py').read().split("with sync_playwright() as pw:")[0].replace("8811","8821"))
with sync_playwright() as pw:
  b=pw.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':800}); p=ctx.new_page(); errs=[]; p.on('pageerror',lambda e:errs.append(str(e)))
  p.goto('http://127.0.0.1:8821/index.html'); p.wait_for_timeout(2500); p.evaluate("async()=>{await navigator.serviceWorker.ready}"); p.reload(); p.wait_for_timeout(2500)
  ctx.set_offline(True); p.reload(); p.wait_for_timeout(3000)
  chk('Offline: 4.3.8 relaunches from cache with no network',p.evaluate("APP_VERSION")=='4.3.8' and p.evaluate("navigator.onLine")==False)
  p.evaluate("()=>document.querySelectorAll('.modal-bg.on').forEach(m=>m.classList.remove('on'))"); p.evaluate(SEED,'owner')
  p.evaluate("()=>{__closeAll();go('pos');resetPosForm();['sm','sm','sm'].forEach(x=>addPosItemFromProduct(x));document.getElementById('posTypeCredit').checked=true;setPosType('credit');document.getElementById('posCustomer').value='cA';document.getElementById('posDueDate').value=todayStr();calcPosTotals();}")
  p.fill('#posDeposit','3000'); p.select_option('#posDepositMethod','mobile-money'); e0=p.evaluate("()=>__dc().expected"); p.click('#posCheckoutBtn'); p.wait_for_timeout(400)
  p.evaluate("()=>__pay('cB','invB',4000,'cash')")
  r=p.evaluate("()=>({pm:S.get('payments').filter(x=>x.date===todayStr()).map(x=>x.method).sort(),exp:__dc().expected,aud:S.get('auditLog').filter(a=>/^Deposit FCFA 3,000 \\(Mobile Money\\)|^Payment FCFA 4,000 \\(Cash\\)/.test(a.msg)).length})")
  chk('Offline: MoMo deposit + cash repayment stored with correct methods; Expected Cash +4,000 only; both audited',r['pm']==['cash','mobile-money'] and r['exp']-e0==4000 and r['aud']==2,{'r':r,'e0':e0})
  p.wait_for_timeout(1500); p.reload(); p.wait_for_timeout(3000); p.evaluate("()=>document.querySelectorAll('.modal-bg.on').forEach(m=>m.classList.remove('on'))")
  r2=p.evaluate("()=>({pm:S.get('payments').filter(x=>x.date===todayStr()).map(x=>x.method).sort(),aud:S.get('auditLog').filter(a=>/^Deposit FCFA 3,000 \\(Mobile Money\\)|^Payment FCFA 4,000 \\(Cash\\)/.test(a.msg)).length})")
  chk('Offline: after closing/reopening offline, payments, methods and audit persisted',r2['pm']==['cash','mobile-money'] and r2['aud']==2,r2)
  txt=p.evaluate("""async()=>{window.toast=()=>{};let blob=null;const o=URL.createObjectURL;URL.createObjectURL=b=>{blob=b;return o.call(URL,b)};exportBackup();URL.createObjectURL=o;await new Promise(r=>setTimeout(r,400));return blob?await blob.text():''}""")
  chk('Offline: backup export works',len(txt)>100 and '"mobile-money"' in txt)
  n=p.evaluate("()=>{const n=S.get('payments').length;S.set('payments',[]);return n}")
  r3=p.evaluate("""async(txt)=>{const T=[];window.toast=(m,ty)=>T.push((ty||'')+':'+m);handleFile(new File([txt],'b.json',{type:'application/json'}));await new Promise(r=>setTimeout(r,900));
     if(document.getElementById('mConfirm').classList.contains('on'))document.getElementById('mConfirmBtn').click();await new Promise(r=>setTimeout(r,1200));return {T,n:S.get('payments').length,pm:S.get('payments').filter(x=>x.date===todayStr()).map(x=>x.method).sort()}}""",txt)
  chk('Offline: restore works with no network — lost payments come back with their methods',r3['n']==n and r3['pm']==['cash','mobile-money'] and any(t.startswith('success:') for t in r3['T']),r3)
  chk('Offline: no JS errors',errs==[],errs); b.close()
srv.shutdown()
print('TOTAL',len(results),'FAIL',sum(1 for _,c in results if not c))
